# Generated by Django 3.2 on 2021-12-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='kurs',
            field=models.ForeignKey(help_text='Wählen Sie den Kurs, welchem die Frage zugewiesen wird', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.kurs'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='name',
            field=models.CharField(help_text='Geben Sie den Namen der Frage ein', max_length=200),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='beschreibung',
            field=models.CharField(help_text='Geben Sie die Beschreibung des Kurses ein', max_length=255),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='name',
            field=models.CharField(help_text='Geben Sie den Namen des Kurses ein', max_length=50),
        ),
    ]
