# Generated by Django 3.2 on 2022-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frage',
            name='antwort1richtig',
            field=models.BooleanField(default=False, help_text='Geben Sie an ob Antwort1 richtig ist', verbose_name='Antwort1 richtig?'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='antwort2richtig',
            field=models.BooleanField(default=False, help_text='Geben Sie an ob Antwort2 richtig ist', verbose_name='Antwort2 richtig?'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='antwort3richtig',
            field=models.BooleanField(default=False, help_text='Geben Sie an ob Antwort3 richtig ist', verbose_name='Antwort3 richtig?'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='antwort4richtig',
            field=models.BooleanField(default=False, help_text='Geben Sie an ob Antwort4 richtig ist', verbose_name='Antwort4 richtig?'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='name',
            field=models.CharField(help_text='Geben Sie hier die Frage ein', max_length=255),
        ),
        migrations.AlterField(
            model_name='richtigoderfalsch',
            name='behauptungrichtig',
            field=models.BooleanField(default=False, help_text='Ist diese Behauptung wahr?', verbose_name='Behauptung wahr?'),
        ),
        migrations.AlterField(
            model_name='richtigoderfalsch',
            name='name',
            field=models.CharField(help_text='Geben Sie hier die Frage ein', max_length=255),
        ),
    ]
