# Generated by Django 3.2 on 2022-03-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_kurs_nachrichtmcfragen_kursname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NachrichtMCFragen',
            new_name='MeldungMCFragen',
        ),
    ]
