# Generated by Django 3.2 on 2022-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_nachrichtmcfragen_meldungmcfragen'),
    ]

    operations = [
        migrations.AddField(
            model_name='meldungmcfragen',
            name='gelesen',
            field=models.BooleanField(default=False),
        ),
    ]
