# Generated by Django 3.2 on 2022-03-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_meldungmcfragen_gelesen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeldungFRFragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kursname', models.CharField(max_length=50)),
                ('frage', models.CharField(max_length=255)),
                ('nachricht', models.CharField(max_length=500)),
                ('benutzername', models.CharField(max_length=50)),
                ('gelesen', models.BooleanField(default=False)),
                ('frageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.frage')),
                ('kursid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.kurs')),
            ],
        ),
    ]
