# Generated by Django 3.2 on 2022-03-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_meldungfrfragen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeldungFRFragen',
            new_name='MeldungRFFragen',
        ),
    ]
