# Generated by Django 3.2 on 2022-03-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_meldungfrfragen_meldungrffragen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meldungrffragen',
            name='frageid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.richtigoderfalsch'),
        ),
    ]
